HomeAssingment/Models/Contact.cs
using HomeAssignment.Repostories;
using System.ComponentModel.DataAnnotations;

namespace HomeAssignment.Models
{
    public class Contact
    {
        [Key]
        [Required(ErrorMessage = "ID is Required")]
        [RegularExpression("[0-9]{9}", ErrorMessage = "ID should be 9 digits long")]
        public string ?Id { get; set; }

        [Required(ErrorMessage = "First Name is Required")]
        [RegularExpression("[A-Za-z\\s\\-]{2,}")]
        public string ?FirstName { get; set; }

        [Required(ErrorMessage = "Last Name is Required")]
        [RegularExpression("[A-Za-z\\s\\-]{2,}")]
        public string ?LastName { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [Range(typeof(DateTime), "1/1/1900", "1/1/2023", ErrorMessage = "Date out of range")]
        public DateTime? BirthDate { get; set; }

        [RegularExpression("[A-Za-z\\s\\-]{2,}", ErrorMessage = "City should be at least 2 letters long")]
        public string? City { get; set; }

        [RegularExpression("[A-Za-z\\s\\-]{2,}", ErrorMessage = "Street should be at least 2 letters long")]
        public string? Street { get; set; }

        [RegularExpression("[0-9]+", ErrorMessage = "House number should be 4 digits long")]
        public int? HouseNumber { get; set; }

        [RegularExpression("[0-9\\-\\+\\(\\)]{9,20}", ErrorMessage = "Invalid phone number")]
        public string? PhoneAtHome { get; set; }

        [RegularExpression("[0-9\\-\\+\\(\\)]{9,20}", ErrorMessage = "Invalid phone number")]
        public string? Phone { get; set; }
    }
}

HomeAssingment/Models/ErrorViewModel.cs
namespace HomeAssignment.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HomeAssingment/Controllers/ContactDetailsController.cs
using HomeAssignment.Models;
using HomeAssignment.Repostories;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Reflection;

namespace HomeAssignment.Controllers
{
    public class ContactDetailsController : Controller
    {
        // GET: ContactDetails
        private readonly IRepository _repository;
        public ContactDetailsController(IRepository repository)
        {
            _repository = repository;
        }
        [HttpGet]
        public IActionResult Index(string id)
        {
            var contact = _repository.GetContact(id);
            if (contact is null)
            {
                return NotFound();
            }
            return View(contact);
        }
        [HttpPost]
        public IActionResult SaveEdit(Contact contact)
        {
            if (contact.Id == null) return BadRequest();

            var IdChanged = _repository.GetContact(contact.Id) == null;

            if (IdChanged)
            {
                ModelState.AddModelError("Id", "ID cannot be modified");
            }

            if (ModelState.IsValid)
            {
                _repository.UpdateContact(contact);
            }
            else TempData["ErrorMessage"] = "Submit failed, one or more parameters are incorrect";
            return View("../ContactDetails/Index", contact);
        }
    }
}

HomeAssingment/Controllers/HomeController.cs
using HomeAssignment.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using HomeAssignment.Repostories;
using System.Text.Json;

namespace HomeAssignment.Controllers
{
    public class HomeController : Controller
    {
        private readonly IRepository _repository;
        public HomeController(IRepository repository)
        {
            _repository = repository;
        }
        public IActionResult Index()
        {
            var contacts = _repository.GetContacts().ToList();
            return View(contacts);
        }
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        [HttpPost]
        public void DeleteMarked([FromBody] List<string> ids)
        {
            foreach (string id in ids)
            {
                _repository.DeleteContact(id);
            }
        }

        public void DeleteAllContacts()
        {
            _repository.DeleteAllContacts();
            RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult SavePhone([FromBody] JsonElement model)
        {
            if (!model.TryGetProperty("id", out var idElement) || idElement.ValueKind != JsonValueKind.Number)
                return BadRequest(new { success = false, message = "Invalid or missing ID" });

            string id = idElement.GetInt32().ToString();

            if (!model.TryGetProperty("phone", out var phoneElement) || phoneElement.ValueKind != JsonValueKind.String)
                return BadRequest(new { success = false, message = "Invalid or missing phone number" });

            string phone = phoneElement.GetString()!;

            var contact = _repository.GetContact(id.ToString());
            if (contact == null)
                return NotFound(new { success = false, message = "Contact not found" });

            contact.Phone = phone;

            var IdChanged = _repository.GetContact(id) == null;

            if (IdChanged)
            {
                ModelState.AddModelError("Id", "ID cannot be modified");
            }

            if (ModelState.IsValid)
            {
                _repository.UpdateContact(contact);
                return Ok(new { success = true });
            }
 
            else
            {
                // Log the exception
                return StatusCode(500, new { success = false, message = "An error occurred while updating the contact" });
            }
        }
    }
}

HomeAssingment/Controllers/NewContactController.cs
using HomeAssignment.Models;
using HomeAssignment.Repostories;
using Microsoft.AspNetCore.Mvc;

namespace HomeAssignment.Controllers
{
	public class NewContactController : Controller
	{
		private readonly IRepository _repository;
		public NewContactController(IRepository repository)
		{
			_repository = repository;
		}

		public IActionResult Index(Contact contact)
		{
            return View(contact);
		}

        [HttpPost]
		public IActionResult CreateContact(Contact contact)
		{
            if (contact.Id == null) return BadRequest();

            var contactExsists = _repository.GetContact(contact.Id) != null;

            if (contactExsists)
            {
                ModelState.AddModelError("Id", "Id already Exists");
            }

            if (ModelState.IsValid)
            {
                _repository.InsertContact(contact);
                return Redirect("/");
            }
            TempData["ErrorMessage"] = "Submit failed, one or more parameters are incorrect";
            return View("Index", contact);
        }
	}
}

HomeAssingment/Views/ContactDetails/Index.cshtml
@model HomeAssignment.Models.Contact

<div>
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script>

		var editing = false;
		var originalValues = {};

		function ToggleEditingMode() {
			const contactFields = document.querySelectorAll("input:not(#id)");
			const editBtn = document.getElementById("edit-btn");
			const saveBtn = document.getElementById("save-btn");

			if (editing) {
				let valuesChanged = false;
				contactFields.forEach((field) => {
					if (field.value !== originalValues[field.id]) {
						valuesChanged = true;
					}
					field.setAttribute("readonly", "true");
				});

				if (valuesChanged) {
					if (!confirm("Are you sure you want to exit edit mode without saving?")) {
						// User cancelled, go back into editing mode
						editing = true;
						return;
					}
				}

				contactFields.forEach((field) => {

					editBtn.textContent = "Edit ✏";
					editBtn.classList.add("btn-warning");
					editBtn.classList.remove("btn-danger");
					field.setAttribute("readonly", "true");
					field.value = originalValues[field.id];
					saveBtn.setAttribute("hidden", "hidden");
				});
			}
			else {
				contactFields.forEach((field) => {
					originalValues[field.id] = field.value;
					editBtn.textContent = "X";
					editBtn.classList.add("btn-danger");
					editBtn.classList.remove("btn-warning");
					field.removeAttribute("readonly");
					saveBtn.removeAttribute("hidden");
				});
			}
			editing = !editing;
		}
	</script>

	<h2>@Model.FirstName @Model.LastName</h2>
	<div class="error-message">@TempData["ErrorMessage"]</div>
	<form asp-action="SaveEdit" class="form-control" id="edit-contact-form">
		<button id="edit-btn" type="button" class="btn btn-warning" onclick="ToggleEditingMode()">Edit ✏</button>
		<div>
			<label for="id">Id</label>
			<input id="id" name="id" type="text" asp-for=Id maxlength="9" pattern="[0-9]{9}" required readonly />
			<span asp-validation-for="Id" class="text-danger"></span>
		</div>
		<div>
			<label for="first-name">First Name</label>
			<input id="first-name" type="text" asp-for=FirstName maxlength="15" pattern="[A-Za-z\s\-]{2,}" title="First name should be at least 2 letters long" required readonly />
			<span asp-validation-for="FirstName" class="text-danger"></span>
		</div>
		<div>
			<label for="last-name">Last Name</label>
			<input id="last-name" type="text" asp-for=LastName maxlength="15" pattern="[A-Za-z\s\-]{2,}" title="Last name should be at least 2 letters long" required readonly />
			<span asp-validation-for="LastName" class="text-danger"></span>
		</div>
		<div>
			<label for="birth-date">Birth Date</label>
			<input id="birth-date" type="date" asp-for=BirthDate readonly />
			<span asp-validation-for="BirthDate" class="text-danger"></span>
		</div>
		<div>
			<label for="city">City</label>
			<input id="city" type="text" asp-for=City maxlength="20" pattern="[A-Za-z\s\-]{2,}" title="City name should be at least 2 letters long" readonly />
			<span asp-validation-for="City" class="text-danger"></span>
		</div>
		<div>
			<label for="street">Street</label>
			<input id="street" type="text" asp-for=Street maxlength="20" pattern="[A-Za-z\s\-]{2,}" title="Street name should be at least 2 letters long" readonly />
			<span asp-validation-for="Street" class="text-danger"></span>
		</div>
		<div>
			<label for="house-number">House Number</label>
			<input id="house-number" type="number" asp-for=HouseNumber maxlength="4" pattern="[0-9]+" readonly />
			<span asp-validation-for="HouseNumber" class="text-danger"></span>
		</div>
		<div>
			<label for="phone-at-home">Phone at Home</label>
			<input id="phone-at-home" type="text" asp-for=PhoneAtHome maxlength="20" pattern="[0-9\-\+\()]+" title="Phone at home cannot include letters" readonly />
			<span asp-validation-for="PhoneAtHome" class="text-danger"></span>
		</div>
		<div>
			<label for="phone">Phone</label>
			<input id="phone" type="text" asp-for=Phone maxlength="20" pattern="[0-9\-\+\()]+" title="Phone cannot include letters" readonly />
			<span asp-validation-for="Phone" class="text-danger"></span>
		</div>
		<div>
			<button id="save-btn" type="submit" class="btn btn-success" hidden>Save</button>
		</div>
	</form>
</div>

HomeAssingment/Views/Home/Index.cshtml
@model List<HomeAssignment.Models.Contact>;

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>

    function RouteToContactDetails(id) {
        window.location.href = '@Url.Action("Index", "ContactDetails")' + '?id=' + id;
    }

    function RouteToNewContact() {
        window.location.href = '@Url.Action("Index", "NewContact")';
    }

    <!-- #editPhone -->
    var editing = false;

    function ToggleEditPhone(id) {
        const phoneInput = document.getElementById(id + "phone");
        const editBtn = document.getElementById(id + "edit-btn");
        const saveBtn = document.getElementById(id + "save-btn");

        if (editing) {
            phoneInput.setAttribute("disabled", true);
            saveBtn.setAttribute("disabled", true);
            editBtn.style.backgroundColor = "#FFA500";
            editBtn.textContent = "Edit ✏";
        } else {
            phoneInput.removeAttribute("disabled");
            saveBtn.removeAttribute("disabled");
            editBtn.style.backgroundColor = "#6D071A";
            editBtn.textContent = "X";
        }
        editing = !editing;
    }

    async function SavePhone(id) {
        const phoneInput = document.getElementById(id + "phone");
        const phone = phoneInput.value;
        const editBtn = document.getElementById(id + "edit-btn");
        const saveBtn = document.getElementById(id + "save-btn");

        const existingWarning = document.getElementById(id + "warning");
        if (existingWarning) {
            existingWarning.remove();
            phoneInput.style.borderColor = "inherit";
        }

        // Validation: Check if phone length is not 10
        if (phone.length !== 10 || !/^\d{10}$/.test(phone)) {
            phoneInput.style.borderColor = "red";
            const warningMessage = document.createElement("div");
            warningMessage.id = id + "warning";
            warningMessage.style.color = "red";
            warningMessage.style.marginTop = "5px";
            warningMessage.style.fontSize = "8px";
            warningMessage.textContent = "Phone number must be 10 digits.";
            phoneInput.insertAdjacentElement("afterend", warningMessage);
            return;
        }

        try {
            const response = await fetch('@Url.Action("SavePhone", "Home")', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({ id: id, phone: phone })
            });

            if (!response.ok) {
                const errorText = await response.text();
                console.error('Server responded with an error:', response.status, errorText);
                throw new Error(`HTTP error! status: ${response.status}`);
            }


            const data = await response.json();

            if (data.success) {
                console.log('Phone number updated successfully.');
                ToggleEditPhone(id);
            } else {
                console.error('Failed to update phone number.');
            }
        } catch (error) {
            console.error('Error parsing JSON:', error);
            console.log('Response text:', await response.text());
        }
    }

    <!-- #endregion -->


    function ResetAllCheckboxes() {
        $('.contacts-body input[type="checkbox"]').prop('checked', false);
    }

    function DeleteContacts() {
        var markedRows = $('.contacts-body input[type="checkbox"]:checked').closest('tr');
        var numEntries = markedRows.length;
        if (numEntries > 0) {
            var message = 'Are you sure you want to delete ' + numEntries + ' entry(s)?';
            if (confirm(message)) {
                var masterCheckboxChecked = $('#master-checkbox').is(':checked');
                if (masterCheckboxChecked) {
                    $.ajax({
                        url: '@Url.Action("DeleteAllContacts")',
                        success: function () {
                            alert('Item(s) deleted');
                            window.location.reload();
                        },
                        error: function () {
                            alert('Error deleting contacts.');
                        }
                    });
                }
                else {
                    var ids = [];
                    console.log(markedRows); // check if markedRows has the expected rows
                    markedRows.each(function () {
                        console.log($(this).attr('id')); // check if this gives the expected id
                        ids.push($(this).attr('id'));
                    });
                    console.log(ids);
                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("DeleteMarked")',
                        data: JSON.stringify(ids),
                        contentType: 'application/json; charset=utf - 8',
                        success: function () {
                            alert('Item(s) deleted');
                            window.location.reload();
                        },
                        error: function () {
                            alert('Error deleting contacts.');
                        }
                    });
                }
                ResetAllCheckboxes();
            }
        }
        else {
            alert('Please select at least one entry to delete.');
        }
    }
    //Apply Route to contact details to every clickable table cell
    $(document).ready(function () {
        $('td.clickable').click(function () {
            var id = $(this).parent().attr('id');
            RouteToContactDetails(id)
        })
    });
    //checkbox checked/uncheked
    $(document).ready(function () {
        $('.contacts-body td.checkbox-cell input[type="checkbox"]').change(function () {
            var checked = $(this).prop('checked');
            var tr = $(this).closest('tr').get(0);
            checked ? tr.classList.add("selected") : tr.classList.remove("selected");
        });
    });

    //master checkbox checked/uncheked
    $(document).ready(function () {
        // Synchronize checkbox state
        $('#master-checkbox').change(function () {
            var checked = $(this).is(':checked');
            $('.contacts-body input[type="checkbox"]').prop('checked', checked).trigger('change');
        });
    });

    // Enable/disable delete button
    $(document).ready(function () {
        $('.contacts-body input[type="checkbox"]').change(function () {
            var isSomeChecked = $('.contacts-body input[type="checkbox"]:checked').length > 0;
            $('#delete-btn').prop('disabled', !isSomeChecked);
            var isNotChecked = !$(this).is(':checked');
            var isMasterChecked = $('#master-checkbox').is(':checked');
            if (isMasterChecked && isNotChecked) {
                $('#master-checkbox').prop('checked', false);
            }
        });
    });

    // reset the state of the checkbox once the route has changed
    $(document).ready(function () {
        $('.route-changer, td:not(.checkbox-cell)').click(function () {
            ResetAllCheckboxes();
        });
    });
</script>

<h3>Contacts Page</h3>
<table id="contacts-table" border="1" class="table table-bordered table-responsive">
    <thead>
        <tr class="table-primary">
            <th id="master-checkbox-cell" class="checkbox-cell"><input id="master-checkbox" type="checkbox" /></th>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Phone Number</th>
        </tr>
    </thead>
    <tbody class="contacts-body">
        @{
            foreach (var contact in Model)
            {
                string contactPhoneId = contact.Id!.ToString() + "phone";
                string editBtnId = contact.Id!.ToString() + "edit-btn";
                string saveBtnId = contact.Id!.ToString() + "save-btn";
                    <tr id="@contact.Id">
                        <td class="checkbox-cell"><input type="checkbox" /></td>
                        <td class="clickable">@contact.Id</td>
                        <td class="clickable">@contact.FirstName</td>
                        <td class="clickable">@contact.LastName</td>
                        <td id="contact-phone">
                            <input id="@contactPhoneId" value="@contact.Phone" disabled />
                            <button id="@editBtnId" class="btn btn-warning" onclick="ToggleEditPhone(@contact.Id)">Edit ✏</button>
                            <button id="@saveBtnId" class="btn btn-success" onclick="SavePhone(@contact.Id)" disabled> Save </button>
                        </td>
                    </tr>
            }
        }
    </tbody>

</table>


<button id="new-contact-btn" class="btn btn-primary route-changer" onclick="RouteToNewContact()">+ New Contact</button>
<button id="delete-btn" class="btn btn-danger" onclick="DeleteContacts()" disabled>Delete</button>

HomeAssingment/Views/NewContact/Index.cshtml
@model HomeAssignment.Models.Contact

<h2>New Contact</h2>
<div class="error-message">@TempData["ErrorMessage"]</div>
<form asp-action="CreateContact" class="form-control" id="new-contact-form">
	<div>
		<label for="id">Id</label>
		<input id="id" name="id" type="text" asp-for=Id maxlength="9" pattern="[0-9]{9}" title="ID should be 9 digits long" required />
		<span asp-validation-for="Id" class="text-danger"></span>
	</div>
	<div>
		<label for="first-name">First Name</label>
		<input id="first-name" type="text" asp-for=FirstName maxlength="15" pattern="[A-Za-z\s\-]{2,}" title="First name should be at least 2 letters long and in English" required />
		<span asp-validation-for="FirstName" class="text-danger"></span>
	</div>
	<div>
		<label for="last-name">Last Name</label>
		<input id="last-name" type="text" asp-for=LastName maxlength="15" pattern="[A-Za-z\s\-]{2,}" title="Last name should be at least 2 letters long and in English" required />
		<span asp-validation-for="LastName" class="text-danger"></span>
	</div>
	<div>
		<label for="birth-date">Birth Date</label>
		<input id="birth-date" type="date" asp-for=BirthDate />
		<span asp-validation-for="BirthDate" class="text-danger"></span>
	</div>
	<div>
		<label for="city">City</label>
		<input id="city" type="text" asp-for=City maxlength="20" pattern="[A-Za-z\s\-]{2,}" />
		<span asp-validation-for="City" class="text-danger"></span>
	</div>
	<div>
		<label for="street">Street</label>
		<input id="street" type="text" asp-for=Street maxlength="20" pattern="[A-Za-z\s\-]{2,}" />
		<span asp-validation-for="Street" class="text-danger"></span>
	</div>
	<div>
		<label for="house-number">House Number</label>
		<input id="house-number" type="number" asp-for=HouseNumber maxlength="4" pattern="[0-9]+" />
		<span asp-validation-for="HouseNumber" class="text-danger"></span>
	</div>
	<div>
		<label for="phone-at-home">Phone at Home</label>
		<input id="phone-at-home" type="text" asp-for=PhoneAtHome maxlength="20" pattern="[0-9\-\+\()]+" title="Phone at home cannot include letters" />
		<span asp-validation-for="PhoneAtHome" class="text-danger"></span>
	</div>
	<div>
		<label for="phone">Phone</label>
		<input id="phone" type="text" asp-for=Phone maxlength="20" pattern="[0-9\-\+\()]+" title="Phone cannot include letters" />
		<span asp-validation-for="Phone" class="text-danger"></span>
	</div>
	<button class="btn btn-success" type="submit">Save contact</button>
</form>

HomeAssingment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HomeAssignment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HomeAssignment.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>